[project]
name = "kandi2025-repo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<=3.14"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "ultralytics>=8.4.9",
]
